name: uttt
description: "Ultimate Tic-Tac-Toe"
publish_to: 'none'
version: 0.0.7

environment:
  sdk: ^3.10.1

dependencies:
  awesome_flutter_extensions: ^2.0.1
  dart_mappable: ^4.6.0
  dartx: ^1.2.0
  extra_alignments: ^1.0.0+1
  flex_color_scheme: ^8.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^3.0.3
  flutter_smart_dialog: ^4.9.8+9
  go_router: ^17.0.0
  intl: any
  logging: ^1.3.0
  package_info_plus: ^9.0.0
  recase: ^4.1.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  tinycolor2: ^3.0.1

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  dart_mappable_builder: ^4.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - docs/


  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
